### ISSUE TITLE
Complete Back End Challenge Overhaul

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#44]
# Complete Back End Challenge Overhaul
## Mission

Our goal is to create new challenges teaching `npm`, `node`, `express`, and `mongoose`. These will replace the NodeSchool modules currently in use. There are several reasons behind this decision:
- Some NodeSchool challenges are unmaintained / buggy
- The `how-to-npm`-challenges cover too advanced topics to fit with our curriculum **(creating & publishing npm packages)**
- We want to enable as much learning as possible in the browser, without requiring installations or local Dev-environment setup.
## Action plan:
1. Get the npm challenges working with @Greenheart's testing tool as a proof of concept :white_check_mark: 
2. @Greenheart and @Em-Ant will create the remaining challenges and their tests using @Greenheart's prototype
3. Then create a version of the HyperDev boilerplate that passes all the tests to ensure they can indeed be passed
4. Make all those tests fail again by removing necessary code. This will serve as the starting project that campers fork on HyperDev
5. @quincylarson and @BerkeleyTrue will implement the UI for these challenges on FCC's beta branch, which hits the appropriate end points and stores the campers' project URL
6. Once @BerkeleyTrue and @quincylarson have finished preparing FCC, we will transfer the prototype's instructions and tests over to Free Code Camp's JSON seed files so these will replace the existing back end challenges in FCC's curriculum.

We are folding the following issues into this one:
Back End Challenges: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/26
Applied InfoSec: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/25
Applied QA: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/24
Automated testing: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/23
## Challenge Structure - `camper-stories`
- [ ] Campers can see each topic (i. e. npm, node, express) as a section in the FCC map
- [ ] Each section on the FCC map corresponds to a **base project** on hyperdev, containing **seed code & utility functions** FCC will use to verify challenges. This base project is linked in the instructions for the first challenge of each section.
- [x] Campers can "remix" a base project on hyperdev to create their own copy.
- [ ] Before they continue learning, they need to enter the URL to their remixed hyperdev project.
- [ ] For each challenge in each section, campers can find instructions **on the corresponding FCC challenge page**
- [ ] To complete a challenge, campers modify their hyperdev project.
- [ ] A button on the FCC challenge page is used to run tests
- [ ] Campers can see test results and a  **hardcoded error-messages of what they have failed to yet accomplish**
## List of Challenges

See [#26](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/26)
#### Status:
- [x] Challenge instructions ([View them below :100: :sparkles: ](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44#issuecomment-240259994))
- [x] Tests for every challenge available in `tests.js` of [the backend tester prototype](https://hyperdev.com/#!/project/marsh-glazer)
- [x] Solutions for every challenge available in `tests.js` (as a property of every test-object)
- [x] Seed Code for each challenge **(N/A)** - Campers start with a minimal `package.json` that's already in the boilerplate - then all challenges build on top of each other.
- [x] [Boilerplate HyperDev project](https://hyperdev.com/#!/project/red-moose) ready to be _remixed_ by campers
#### Challenges:
- [ ] [Related to #45 ](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/45) Some kind of intro (see notes in the beginning of [the npm challenges posted below](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44#issuecomment-240259994))
  Teach the difference between npm in hyperdev and npm used from terminal. 
  npm is whole ecosystem but we're just touching the fundamental concepts that you need to know right now like adding / removing packages
  Tests: none
- [x] Introduction to package.json - The Core of Any Node.js Project or npm Package
  This challenge is the introduction to package.json - but has the camper adding an author-field to make it interactive.
  Tests: Author changed in JSON.parse(package.json)
- [x] Add a Description to Your package.json
  Tests: Description changed in JSON.parse(package.json)
- [x] Add Keywords to Your package.json
  Tests: Keywords changed in JSON.parse(package.json)
- [x] Add a License to Your package.json
  Tests: License changed in JSON.parse(package.json)
- [x] Add a  Version to Your package.json
  Tests: Version changed in JSON.parse(package.json)
- [x] Expand Your Project With External Packages From npm
  Use some simple library (Moment.js)
  Tests:  The package is in JSON.parse(package.json)
- [x] Manage npm Dependencies by Understanding Semantic Versioning
  Tests: whether the package is of a specific older version
- [x] Use the Tilde-Character to use the Latest Patch Version of a Dependency
- [x] Use the Caret-Character to Use the Latest Minor Version of a Dependency
- [x] Remove a Package From Your Dependencies
  Tests: The package is no longer in JSON.parse(package.json)
#### Hello Node! :white_check_mark:

**Requirement** : `console.log('Hello World')`
#### Basic Express setup :white_check_mark:

**Route**: `GET /` 
**Respond with**:  `Hello Express`
#### Serve HTML using `res.sendFile()` :white_check_mark:

**Route**: `GET /`
**Respond with**: `views/index.html` (it contains `<h1>Hello, HTML!</h1>` and has a style link in it)
#### Serve a Stylesheet with the `express.static()` middleware :white_check_mark:

**Route**: `/style.css`
**Respond with**: the css stylesheet. It has the `body {...}` selector
#### Respond with JSON :white_check_mark:

**Route**: `GET /json`
**Respond with**: `{ "message": "Hello json" }`
#### Use the `.env`-file to store (secret) configuration :white_check_mark:

**Env var**: `TEXT_STYLE=uppercase`
**Route**: `GET /json`
**Respond with**: `if process.env.TEXT_STYLE === upprecase => { "message": "HELLO JSON" } else => { "message": "Hello json" }`
#### App level Middleware - logger :white_check_mark:

**Description**: Simple logger, for all the routes. Required format: `method route - ip`. 
**Route**: all
#### Simple Time middleware in a route ( Time Server ) :white_check_mark:

**Description** :Augment the `req` object with `req.time = new Date` in a **route** middleware
**Route**: `/now`
**Respond with**: `{time: req.time.toString()}`
#### The `req.params` object :white_check_mark:

**Route**: `GET /:word/echo`
**Respond with**: `{echo: <word>}`
#### The `req.query` object :white_check_mark:

**Route**:  `GET /name?first=<firstname>&last=<lastname>`
**Respond with**: `{name: '<firstname> <lastname>'}`
#### Install and configure the `body-parser` module :white_check_mark:

**Description ideas**: differences between `urlencoded`, `json`, and `multipart` (not handled by body-parser).
#### Receive a `POST` request and use the `req.body` :white_check_mark:

**Route**: `POST /name`,
**Body**: `{first: <firstname>, last: <lastname>} url-encoded`,
**Respond with**: `{name: '<firstname> <lastname>'}`
#### Prerequisites:
- Being able to create an **mLab** db instance, and get the URI
#### Introduction :hourglass:
- What is an DB?
- **CRUD** Operations
- SQL vs NoSQL
- What is Mongo DB?
- What is an ORM?
- What is Mongoose?
#### Setup :white_check_mark:
- add `mongodb` and `mongoose` to package.json
- import `mongoose`
- connect to the DB (the url from earlier setup)
#### Schemas and Models :white_check_mark:
- **Schemas** map to `MongoDB` collections. 
- You can combine multiple schemas to create complex **Models**
- A Model is a **Constructor** that allows You to create object instance, called **Documents**
- Schema types (`String`, `Number`, `...`)
- Basic validation (`required`, `unique`)
- `default` values
#### Create  :white_check_mark:
- **Note**: Interactions with the db cannot be in the main flow, in the server code. We need to have put code inside callbacks. `done()` is a callback that tells us that we can proceed after completing an async operation. It should be called as `done(null, data)` on success or `done(err)` on error, according to the `Node` convention.
- Create then Save - one document at time
- Create many docs -  `Model.create([{...},{...},..,])` (useful for seeding the db)
#### Read :white_check_mark:
- `Model.find()` 
- `Model.findOne()`
- `Model.findById()` 
#### Update :white_check_mark:
- Find, Edit then Save
- `findOneAndUpdate()` or `findbyIdAndUpdate()`
#### Delete :white_check_mark:
- Delete **one** document : `findByIdAndRemove()` or `findOneAndRemove()`
- Delete **many** documents : `Model.remove({criteria: ...}, cb)`
#### Chain Query helpers :white_check_mark:
- `.limit()`
- `.sort()`
- `.select()`
- `.exec()`
### 5. Information security with Helmet.js (check this [comment](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44#issuecomment-242342307)) :white_check_mark:

**[`Helmet.js`](https://github.com/helmetjs/helmet)**
#### Description

It helps to secure Express apps by setting various **HTTP headers**.
It is a collection of 10 middleware functions that set headers:
- [contentSecurityPolicy](https://github.com/helmetjs/csp) for setting Content Security Policy
- [dnsPrefetchControl](https://github.com/helmetjs/dns-prefetch-control) controls browser DNS prefetching
- [frameguard](https://github.com/helmetjs/frameguard) to prevent clickjacking
- [hidePoweredBy](https://github.com/helmetjs/hide-powered-by) to remove the X-Powered-By header
- [hpkp](https://github.com/helmetjs/hpkp) for HTTP Public Key Pinning :no_entry_sign: 
- [hsts](https://github.com/helmetjs/hsts) for HTTP Strict Transport Security
- [ieNoOpen](https://github.com/helmetjs/ienoopen) sets X-Download-Options for IE8+
- [noCache](https://github.com/helmetjs/nocache) to disable client-side caching
- [noSniff](https://github.com/helmetjs/dont-sniff-mimetype) to keep clients from sniffing the MIME type
- [xssFilter](https://github.com/helmetjs/x-xss-protection) adds some small XSS protections
#### Challenges Structure
- We should not include [hpkp](https://github.com/helmetjs/hpkp) because it is only applicable to _https_ with certificates.
- For each Middleware :
  1. Introduce the vulnerability addressed,
  2. Ask the camper to mount and configure the middleware,
  3. Test the results, checking the response headers, and the middleware stack for the main route.
- At the end show how the same result can be obtained simply with `app.use(helmet({<config>...}))`

**Note**: There is a lot of information that could (should) be added about this argument, e.g. Input sanitization, [CSRF](https://github.com/expressjs/csurf), secure cookies settings, RegEx DoS, dependencies auditing ([nsp](https://nodesecurity.io/)). See [Express Security Best Parctices](https://expressjs.com/en/advanced/best-practice-security.html).

**Comment by Greenheart** [comment]
# The npm-Challenge Descriptions for FCC's New Backend Curriculum

## 1. Manage Node.js projects and npm packages using package.json

##### NOTE: Text until challenge 1.1 starts should be moved to the introduction page for the backend challenges
We need to explain backend development on a high level before we jump into these npm challenges. It doesn't feel like a high-level description of Node.js and backend development in general fits as part of a challenge.

### The introduction below could fit under "Introduction to Node Package Manager (npm)".

npm is the package manager of the JavaScript ecosystem and is a great place to find packages (libraries or other tools) to use in your project. It's also a platform to share tools you've built with other developers. However, the following challenges focus merely on how you can use existing packages to improve your projects.

##### Caveats With the Environment You'll Use During Our Backend Challenges:
Since you will complete these challenges using HyperDev, you get a good development environment and can start learning instantly. At the same time, this introduces a caveat you need to be aware of. Since you will not manage your npm project by typing commands in a terminal, you will use npm in a different way compared to your future projects. At the same time as this may seem counterintuitive, we believe this caveat is a good thing because it allows us to teach you how npm works behind the scenes - which will give you a much deeper understanding when you start using npm through a terminal.

Analogy for the three pillars of fullstack js
Node - Floor of the room - bricks / Cameras
npm - npm furniture / actors
express - Walls / blueprints / get started quickly / script

Fullstack javascript apps are written in Node.js structured around the express framework

---

### 1.1 Introduction to package.json - The Core of Any Node.js Project or npm Package
The file `package.json` is the center of any Node.js project or npm package. It stores information about your project just like the `<head>`-section in a `HTML` document describes the content of a webpage. The `package.json` consists of a single `JSON`-object where information is stored in `"key": value`-pairs. There are only two required fields in a minimal `package.json` - `name` and `version` - but it's a good practice to provide additional information about your project that could be useful to future users or maintainers.

##### The author-field
If you go to the **HyperDev**-project that you set up previously and look at on the left side of your screen, you'll find the *file tree* where you can see an overview of the various files in your project. Under the file tree's **back-end** section, you'll find `package.json` - the file that we'll be improving in the next couple of challenges.

One of the most common pieces of information in this file is the `author`-field that specifies who's the creator of a project. It can either be a string or an object with contact details. The object is recommended for bigger projects but in our case, a simple string like the following example will do.

`"author": "Jane Doe",`

##### Instructions
Add your name to the `author`-field in the `package.json` of your **HyperDev** project.

Remember that you're writing `JSON`:
* All field-names must use double-quotes (`"`), e.g. `"author"`
* All fields must be separated with a comma (`,`)


---


### 1.2 Add a Description to Your package.json
The next part of a good `package.json` is the `description`-field, where a short but informative description about your project belongs.

If you some day plan to publishing a package to npm, remember that this is the string that should sell your idea to the user when they decide whether to install your package or not. However, that's not the only use case for the `description`: Since it's a great way to summarize what a project does, it's just as important for your normal Node.js-projects to help other developers, future maintainers or even your future self understand the project quickly.

Regardless of what you plan for your project, a description is definitely recommended. Let's add something similar to this:

`"description": "A project that does something awesome",`

##### Instructions
Add a `description` to the `package.json` in your **HyperDev** project.

Remember to use double-quotes for field-names (`"`) and commas (`,`) to separate fields.


---


### 1.3 Add Keywords to Your package.json
The `keywords`-field is where you can describe your project using related keywords.

##### Example
`"keywords": [ "descriptive", "related", "words" ],`

As you can see, this field is structured as an *array* of double-quoted *strings*.

##### Instructions
Add an array of suitable strings to the `keywords`-field in the `package.json` of your **HyperDev** project.

One of the keywords should be `freecodecamp`.


---


### 1.4 Add a license to your package.json
**TODO:** This challenge could be used to inspire more people to develop OSS - we should really improve this description.

The `license`-field is where you inform users of your project what they are allowed to do with it.

Some common licenses for open source projects include `MIT` and `BSD`. http://choosealicense.com is a great resource if you want to learn more about what license could fit your project.

License information is not required. Copyright laws in most countries will give you ownership of what you create by default. However, it's always a good practice to explicitly state what users can and can't do.

##### Example
`"license": "MIT",`

##### Instructions
Fill the `license`-field in the `package.json` of your **HyperDev** project as you find suitable.


---

### 1.5 Add a Version to Your package.json
The `version` is together with `name` one of the required fields in a `package.json`. This field describes the current version of your project.

##### Example
`"version": "1.2",`

##### Instructions
Add a `version` to the `package.json` in your **HyperDev** project.


---


### 1.6 Expand your project with external packages from npm
One of the biggest reasons to use a package manager is their powerful dependency management. Instead of manually having to make sure that you get all dependencies whenever you set up a project on a new computer, npm automatically installs everything for you. But how can npm know exactly what your project needs? Meet the `dependencies`-section of your `package.json`.

In the `dependencies`-section, packages your project require are stored using the following format:
```json
"dependencies": {
  "package-name": "version",
  "express": "4.14.0"
}
```


##### Instructions
Add version `2.14.0` of the package `moment` to the `dependencies`-field of your `package.json`

Moment is a handy library for working with time and dates.


---


### 1.7 Manage npm Dependencies By Understanding Semantic Versioning
Versions of the npm packages in the `dependencies`-section of your `package.json` follow what's called [Semantic Versioning (SemVer)](http://semver.org), an industry standard for software versioning aiming to make it easier to manage dependencies. Libraries, frameworks or other tools published on npm should use SemVer in order to clearly communicate what kind of changes that projects who depend on the package can expect if they update.

SemVer doesn't make sense in projects without public APIs - so unless your project is similar to the examples above, use another versioning format.

##### So why do you need to understand SemVer?
Knowing SemVer can be useful when you develop software that use external dependencies (which you almost always do). One day, your understanding of these numbers will save you from accidentally introducing breaking changes to your project without understanding why things *"that worked yesterday"* suddenly doesn't.

This is how Semantic Versioning works according to the official website:
> Given a version number MAJOR.MINOR.PATCH, increment the:
```text
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

This means that `PATCH`es are bug fixes and `MINOR`s add new features but neither of them break what worked before. Finally, `MAJOR`s add changes that **won't work with earlier versions**.

##### Example
A semantic version number: `1.3.8`

##### Instructions
In the `dependencies`-section of your `package.json`, change the version of `moment` to match `MAJOR` version 2, `MINOR` version 10 and `PATCH` version 2


---


### 1.8 Use the tilde-character to always use the latest patch version of a dependency
In the last challenge, we told npm to only include a specific version of a package. That's a useful way to freeze your dependencies if you need to make sure that different parts of your project stay compatible with each other. But in most use cases you don't want to miss bug fixes, since they often include important security patches and (hopefully) don't break things in doing so.

To allow a npm dependency to get updated to the latest `PATCH`-version, you can prefix the dependency's version with the tilde-character (`~`). In `package.json`, our current rule for how npm may upgrade `moment` is to use a specific version only (`2.10.2`), but we want to allow the latest `2.10.x`-version.


##### Example
`"some-package-name": "~1.3.8"` allows updates to any `1.3.x` version.


##### Instructions
Use the tilde-character (`~`) to prefix the version of `moment` in your `dependencies` and allow npm to update it to any new `PATCH` release.

Note that the version numbers themselves not should be changed.


---


### 1.9 Use the caret-character to use the latest minor version of a dependency
Similar to how the tilde (`~`) we learned about in the last challenge allow npm to install the latest `PATCH` for a dependency, the caret (`^`) allows npm to install future updates as well. The difference is that the caret will allow both `MINOR` updates and `PATCH`es.

At the moment, your current version of `moment` should be `~2.10.2` which allows npm to install to the latest `2.10.x`-version. If we instead were to use the caret (`^`) as our version prefix, npm would instead be allowed to update to any `2.x.x`-version.

##### Example
`"some-package-name": "^1.3.8"` allows updates to any `1.x.x` version.


##### Instructions
Use the caret-character (`^`) to prefix the version of `moment` in your `dependencies` and allow npm to update it to any new `MINOR` release.

Note that the version numbers themselves not should be changed.


---


### 1.10 Remove a package from your dependencies
Now you've tested a few ways you can manage dependencies of your project by using the `package.json`'s `dependencies`-section. You've included external packages by adding them to the file and even told npm what types of versions you want by using special characters as the tilde (`~`) or the caret (`^`).

But what if you want to remove an external package that you no longer need? You might already have guessed it - Just remove the corresponding `"key": value`-pair for that from your `dependencies`. 

This same method applies to removing other fields in your `package.json` as well.


##### Instructions
Remove the package `moment` from your `dependencies`.

**Comment by QuincyLarson** [comment]
@Greenheart these directions are excellent! I am really excited about all the forward progress you're making. 

From the top issue, it looks like you have also made a lot of headway with Node and Express. 

Keep up the hard work. This is all coming together.

**Comment by Em-Ant** [comment]
@Greenheart we need to edit a little the npm challenges. The name and the version fields are the minimal requirement for a valid package.json [npm docs](https://docs.npmjs.com/files/package.json). So version should be the first challenge

**Comment by Greenheart** [comment]
@Em-Ant I guess it makes sense to teach it in the beginning. 

Do **version** have to be the first challenge though? Or could it be challenge **1.2**? 
The instructions of **1.1** cover some necessary introductory information and has a long description because of that. The author-field is easy to explain - and I think it suits well for a first challenge.

**Comment by Em-Ant** [comment]
1.2

**Comment by Em-Ant** [comment]
@Greenheart we also need to write about the `start` script, and the `main` field in the package.json challenges.

**Comment by QuincyLarson** [comment]
Based on our conversation on Google Hangouts, I recommend you spend today:
1. Creating a list of Mongoose challenges
2. Creating the code and tests for these
3. Creating a list of Helmet and Chai challenges
4. Creating the code and tests for these

The top priority is for us to cover Mongoose in some level of detail so campers are prepared for the API & Microservice projects. 

The secondary priority is to have some level of coverage of Helmet and Chai.

Later we can work on making tests to verify the user stories for the dynamic web app projects.

Again, @BerkeleyTrue @Em-Ant and I can work on integrating all the testing framework into our platform after @Greenheart has started his busy internship next week.

**Comment by Em-Ant** [comment]
# 3. FCC Mongo & Mongoose Challenges

## Overview

### Prerequisites:
* Being able to create an **mLab** db instance, and get the URI

### Introduction to this section :hourglass: 
* What is an DB?
* **CRUD** Operations
* SQL vs NoSQL
* What is Mongo DB?
* What is an ORM?
* What is Mongoose?

### Setup :white_check_mark: 
* add `mongodb` and `mongoose` to package.json
* import `mongoose`
* connect to the DB (the url from earlier setup)

### Schemas and Models :white_check_mark: 
* **Schemas** map to `MongoDB` collection. 
* You can combine multiple schemas to create complex **Models**
* A Model is a **Constructor** that allows You to create object instance, called **Documents**
* Schema types (`String`, `Number`, `...`)
* Basic validation (`required`, `unique`)
* `default` values

### Create  :white_check_mark: 
* **Note**: Interactions with the db cannot be in the main flow, in the server code. We need to have code inside callbacks. `done()` is a callback that tells us that we can proceed after completing an async operation. It should be called as `done(null, data)` on success or `done(err)` on error, according to the `Node` convention.
* Create then Save - one document at time
* Create many docs -  `Model.create([{...},{...},..,])` (useful for seeding the db)

### Read :white_check_mark: 
* `Model.find()` 
* `Model.findOne()`
* `Model.findById()` 

### Update :white_check_mark: 
* Find, Edit then Save
* `findOneAndUpdate()` or `findbyIdAndUpdate()`

### Delete :white_check_mark: 
* Delete **one** document : `findByIdAndRemove()` or `findOneAndRemove()`
* Delete **many** documents : `Model.remove({criteria: ...}, cb)`

### Chaining query methods :construction: 
* `.limit()`
* `.sort()`
* `.select()`
* `.exec()`

**Comment by Greenheart** [comment]
@Em-Ant Great work! Keep it up man! :smile:

**Comment by QuincyLarson** [comment]
@Em-Ant you have some amazing momentum. Keep it up. Let me know if I can do anything to help :)

**Comment by Em-Ant** [comment]
# 4. FCC Applied InfoSec Challenges

## Overview

### [`Helmet.js`](https://github.com/helmetjs/helmet)

#### Description
It helps to secure Express apps by setting various **HTTP headers**.
It is a collection of 10 middleware functions that set headers:

- [contentSecurityPolicy](https://github.com/helmetjs/csp) for setting Content Security Policy
- [dnsPrefetchControl](https://github.com/helmetjs/dns-prefetch-control) controls browser DNS prefetching
- [frameguard](https://github.com/helmetjs/frameguard) to prevent clickjacking
- [hidePoweredBy](https://github.com/helmetjs/hide-powered-by) to remove the X-Powered-By header
- [hpkp](https://github.com/helmetjs/hpkp) for HTTP Public Key Pinning :no_entry_sign: 
- [hsts](https://github.com/helmetjs/hsts) for HTTP Strict Transport Security
- [ieNoOpen](https://github.com/helmetjs/ienoopen) sets X-Download-Options for IE8+
- [noCache](https://github.com/helmetjs/nocache) to disable client-side caching :no_entry_sign: 
- [noSniff](https://github.com/helmetjs/dont-sniff-mimetype) to keep clients from sniffing the MIME type
- [xssFilter](https://github.com/helmetjs/x-xss-protection) adds some small XSS protections

#### Challenges Structure

- We should not include [hpkp](https://github.com/helmetjs/hpkp) because it is only applicable to *https* with certificates, and [noCache](https://github.com/helmetjs/nocache) because often is not appropriate, and it would introduce performance penalties.

- For each Middleware :
  1. Introduce the vulnerability addressed,
  2. Ask the camper to mount and configure the middleware,
  3. Test the results, checking the response headers, and the middleware stack for the main route.

- As the the last challenge show how the same result can be obtained simply with `app.use(helmet({<config>...}))`

**Note**: There is a lot of information that could (should) be added about this argument, e.g. Input sanitization, [CSRF](https://github.com/expressjs/csurf), secure cookies settings, RegEx DoS, dependencies auditing ([nsp](https://nodesecurity.io/)). See [Express Security Best Parctices](https://expressjs.com/en/advanced/best-practice-security.html).

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! We've loaded these challenges into the seed files and plan to deploy them to beta as soon as possible. 

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
