### ISSUE TITLE
Challenges that teach debugging

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#47]
Our goal with these debugging challenges is to teach campers a few tricks they can use to more effectively solve our algorithm challenges. Note that, like all our other challenges, these should be interactive and not involve using external resources - only things that they can do right in the code editor on Free Code Camp, which we can then test.

- [x] [Use console.log to Check the Value of a Variable](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243160968)
- [x] [Using typeof to Check the Type of a Variable](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243161254)
- [x] [Catch Misspelled Variable and Function Names](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243162882)
- [x] [Catch Unclosed Parentheses,  Brackets, Braces and Quotes](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243163631)
- [x] [Catch Mixed Usage of Single and Double Quotes](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243240495)
- [x] [Catch Use of Assignment operator Instead of Equality Operator (= VS == and ===)](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243241537)
- [x] [Catch Missing Open and Closing Parenthesis After a Function Call (newFunction() is different than newFunction)](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243243746)
- [x] [Catch Arguments that are Passed in the Wrong Order when Calling a Function](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243277471)
- [x] [Catch "Off By One" Errors when Using Indexing](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243443573)
- [x] [Use Caution when Reinitializing Variables inside a Loop](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243425505)
- [x] [Prevent Infinite Loops with a Valid Terminal Condition](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243507085)

**Comment by HKuz** [comment]
I have some notes on debugging (and plenty of personal experience) that I can list here. In terms of methods to debug, the existing console.log and typeof hit the nail on the head. Not sure if we want to tell campers about code-checking tools like JSLint. If we also want to point out some common syntax and runtime 'gotchas', here are some ideas:

- Use correct spelling of variable and function names
- Make sure all opening parentheses/brackets/braces/quotes have a closing pair
- Take care when mixing single and double quotes
- Avoid using the assignment (=) operator when checking for equality (== or ===)
- Include ()'s after the function name when calling it (even if there are no parameters) - newFunction() is different than newFunction
- Pass arguments in the right order and number (provide all required arguments) when calling a function
- Take care when reinitializing variables in a loop

The phrasing of these could use some help, but it's a start. I can help create these likely starting Monday, only issue may be if we want to write the code in ES6 (given this topic comes after those lessons). I'm learning it now myself, and am no expert. There's a touch of irony if the debugging section were written in bum code. I can take a shot, but if there's someone else that could review my work once it's up or note if any of these 'bugs' aren't an issue in ES6, would be hugely appreciated.

**Comment by QuincyLarson** [comment]
@HKuz excellent idea. We could essentially present them with some code that doesn't run and have them fix it. This would reinforce the nature of each of these types of bugs. I've added your your suggested challenge ideas to the list above. Would you have time to help design these?

**Comment by HKuz** [comment]
@QuincyLarson yes, that's a great approach! I'll have time to work on these - I'm pulling a few positioning challenges together for the vis design team and should have those done sometime tomorrow/Monday, then I can start these. Oh, and happy birthday to your daughter :)

**Comment by QuincyLarson** [comment]
@HKuz awesome! I think these will be a welcomed addition to our early challenges. Thanks for your help with them. And if you think of any other common typos or mistakes developers make, feel free to add to the list of challenges in my original post on this thread (you can edit it since you have write permission). 

Her birthday party was amazing. I'll share photos soon if you're interested in watching a one-year-old utterly destroy a birthday cake! 👶

**Comment by HKuz** [comment]
@QuincyLarson that's fantastic on the cake smash! I have a 3-yo niece and two 2-yo nephews, who were all surprisingly tame with their 1st birthday treats. That's a really fun age, especially watching their language progression (and I fully realize that as their aunt, I usually don't see them at their worst, but still).

And as for challenges, I'll try to think of any others. There are some looping errors that pop up in the Gitter JavaScript help room somewhat frequently. I'll get my thoughts organized and edit the list as needed.

**Comment by QuincyLarson** [comment]
@HKuz it's weird posting a baby picture on a GitHub issue, but here goes:

![](https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-9/14141685_10154460571357328_3506548620164732475_n.jpg?oh=cfa407f1376c240d26ee04b21b1a7da9&oe=583846F0)

@HKuz yes - tips for preventing infinite loops would be great, though it might be dangerous to test them. For example, not incrementing an i variable, or accidentally having a condition that's always true in a for loop.

You can get to those if you get to them. My humble advice would be to focus on building the ones we have listed first 😄

**Comment by HKuz** [comment]
@QuincyLarson HAHA - that's amazing! She looks so happy, and shipit squirrel approves of her cake-wrecking efficiency :shipit:  

I've got a couple of these challenges (and some intro text to come) in the pipeline. Plan is to be ~2/3 done by the end of today, then finish the last couple tomorrow. I made a few tweaks to the first two challenges for console.log and typeof to add the 'debugging' theme in. If you don't want to change existing challenges, no worries, just ignore those posts.

**Comment by HKuz** [comment]
# Use console.log to Check the Value of a Variable

## Challenge Description

Both Chrome and Firefox have excellent JavaScript consoles, also known as DevTools, for debugging your JavaScript.

You can find Developer tools in your Chrome's menu or Web Console in FireFox's menu. If you're using a different browser, or a mobile phone, we strongly recommend switching to desktop Firefox or Chrome.

--NEW TEXT, INSTRUCTIONS, AND TEST BELOW HERE

The console.log() method, which "prints" the output of what's within its parentheses to the console, will likely be your most helpful debugging tool. Placing it at strategic points in your code can show you the intermediate values of variables. It's good practice to have an idea of what the output should be before looking at what it is. Having check points to see the status of your calculations throughout your code will help narrow down where the problem is.

Here's an example to print 'Hello world!' to the console:

```js
console.log('Hello world!')
```

## Instructions (NEW)

Use the `console.log()` method to print the value of the variable `a` where noted in the code.

## Challenge Seed

```js
"use strict"

let a = 5;
let b = 1;
a++;
// Use console.log() below this line to check the value of a, it should output 6


let sumAB = a + b;
console.log(sumAB);
```

## Challenge Tests

```
assert(code.test(/console\.log\(a\)/gi)), 'message: Use <code>console.log()</code> to check the value of the variable <code>a</code>.');
```

## Challenge Solution

```js
"use strict"

let a = 5;
let b = 1;
a++;
// Use console.log() to check the value of a, it should output 6
console.log(a);

let sumAB = a + b;
console.log(sumAB);
```

**Comment by HKuz** [comment]
# Using typeof to Check the Type of a Variable

## Challenge Description

You can use typeof to check the data structure, or type, of a variable.

--NEW TEXT BEGIN (would be part of first paragraph)

This is useful in debugging when you're working with multiple data types. If you think you're adding two numbers, but one is actually a string, the results will be different. Type errors can lurk in calculations or function calls. Especially take care when you're accessing and working with external data in the form of a JavaScript object (JSON).

```js
let number7 = 7;
let string3 = "3";
number7 + string3 // output is "73", not 10
```

JavaScript recognizes six primitive (immutable) data types: Boolean, Null, Undefined, Number, String, and Symbol (new with ES6) and one type for mutable items: Object.


--NEW TEXT END - NO CHANGE TO TESTS

Note that in JavaScript, arrays are technically a type of object.

Try using typeof on each of the following to see which types they have.

console.log(typeof "");

console.log(typeof 0);

console.log(typeof []);

console.log(typeof {});


## Instructions

See above.

## Challenge Seed

N/A

## Challenge Tests

```
assert(true, 'message: Nothing to see here.');
```

## Challenge Solution

N/A

**Comment by HKuz** [comment]
# Catch Misspelled Variable and Function Names

## Challenge Description

Now that we've covered the two primary ways to check intermediate values and types of program output, let's get into the common forms that bugs take. One syntax-level issue that folks with fast typing skills can commiserate with is the humble spelling error. Transposed, missing, or mis-capitalized characters in a variable or function name will have the browser looking for an object that doesn't exist - and complain in the form of a reference error. As you know, JavaScript variable and function names are case-sensitive.

## Instructions

Fix the two spelling errors in the code so the `netWorkingCapital` calculation works.

## Challenge Seed

```js
"use strict"

let receivables = 10;
let payables = 8;
let netWorkingCapital = recievables - payable;
console.log(`Net working capital is: ${netWorkingCapital}`);
```

## Challenge Tests

```
assert(netWorkingCapital === 2, 'message: Check the spelling of the two variables used in the <code>netWorkingCapital</code> calculation, the console output should show that "Net working capital is: 2".');

assert(!code.test(/recievables/g), 'message: Make sure the <code>receivables</code> variable is spelled correctly.');

assert(!code.test(/payable\s*?;/g), 'message: Make sure the <code>payables</code> variable is spelled correctly.');
```

## Challenge Solution

```js
"use strict"

let receivables = 10;
let payables = 8;
let netWorkingCapital = receivables - payables;
console.log(`Net working capital is: ${netWorkingCapital}`);
```

**Comment by HKuz** [comment]
# Catch Unclosed Parentheses,  Brackets, Braces and Quotes

## Challenge Description

Another syntax error to watch out for is that all opening parentheses, brackets, curly braces, and quotes have a closing pair. This tends to happen when you are editing existing code and inserting items with one of the pair types. Also, take care when you're nesting code blocks into others, such as adding a callback function as an argument to a method.

One way to avoid this mistake is as soon as you type the opening character, immediately type the closing match, then move your cursor back between them and continue coding. Fortunately, most modern code editors generate the second half of the pair automatically.

## Instructions

Fix the two pair errors so the code runs without issues.

## Challenge Seed

```js
"use strict"

let myArray = [1, 2, 3;
let addSeven = myArray.map((val => val + 7);
console.log(`addSeven array is: ${addSeven}`);
```

## Challenge Tests

```
assert(addSeven[0] === 8 && addSeven[1] === 9 && addSeven[2] === 10, 'message: Check the array and the <code>.map()</code> method for matching pairs. The console output should show that <code>addSeven</code> is <code>[8, 9, 10]</code>.');

assert(code.test(/3\s*?\]\s*?;/gi), 'message: The array should be enclosed with a matching set of brackets.');

assert(code.test(/val\s*?\)\s*?=>/gi), 'message: The <code>.map()</code> method's parameter should be enclosed with a matching set of parentheses.');
```

## Challenge Solution

```js
"use strict"

let myArray = [1, 2, 3];
let addSeven = myArray.map((val) => val + 7);
console.log(`addSeven array is: ${addSeven}`);
```

**Comment by HKuz** [comment]
# Introduction to the Debugging Challenges

## Challenge Description

Debugging is a valuable and (unfortunately) necessary tool for programmers. It follows the testing phase of checking if your code works as intended, and discovering it does not. Debugging is the process of routing out exactly what isn't working and fixing it.

After spending time creating a brilliant block of code, it can be tough realizing it may have a flaw or two. These issues generally come in three forms - 1) syntax errors that prevent a program from running, 2) runtime errors when code fails to execute or has unexpected behavior, and 3) semantic (or logical) errors when code doesn't do what it's meant to. Modern code editors (and experience) can help identify syntax errors, but semantic and runtime errors can be harder to pin down. They may cause your program to crash, make it run forever, or give incorrect output. Think of debugging as trying to understand why your code is behaving the way it is.

Example of a syntax error - often detected by the code editor:

```js
funtion willNotWork( {
  console.log("Yuck");
}
// "function" keyword is misspelled and there's a missing parenthesis
```

Example of a runtime error - often detected while the program executes:

```js
function loopy() {
  while(true) {
      console.log("Hello, world!");
  }
}

loopy(); // This kicks off an infinite loop, which may crash your browser
```

Example of a semantic error - often detected after testing code output:

```js
function calcAreaOfRect(w, h) {
  return w + h; // This should be w * h
}

let myRectArea = calcAreaOfRect(2, 3);
// Correct syntax and the program executes, but this gives the wrong answer
```

Debugging is potentially frustrating, but it helps to develop (and follow) a systematic approach of checking the intermediate value and/or type of variables against what you think they should be. You can start with a simple process of elimination - if function A works and returned what it's supposed to, then function B may have the issue. Alternatively, you can start checking values in a block of code from the middle to try to cut the search space in half - a problem here indicates a bug in the first half, if not, it's likely in the second, and so on.

This section will cover a couple helpful tools to find bugs, and some of the common forms they take. Fortunately, debugging is a learnable skill that just requires a little patience and practice to master.

**Comment by HKuz** [comment]
# Catch Mixed Usage of Single and Double Quotes

## Challenge Description

JavaScript allows the use of both single ('') and double ("") quotes to declare a string, and deciding which one to use generally comes down to personal preference. Having two choices is great when your string has contractions or another piece of text that's in quotes. Just be careful that you don't close the string too early, which causes a syntax error.

Examples of mixing quotes:

```js
// These work
const grouchoContraction = "I've had a perfectly wonderful evening, but this wasn't it.";
const quoteInString = "Groucho Marx once said 'Quote me as saying I was mis-quoted.'";

// This is wrong
const uhOhGroucho = 'I've had a perfectly wonderful evening, but this wasn't it.';
```

Of course, if you prefer to only use one style of quotes, then you can escape the ones inside the string by using the backslash escape character:

```js
const allSameQuotes = 'I\'ve had a perfectly wonderful evening, but this wasn\'t it.';
```

## Instructions

Fix the string so it either uses different quotes for the `href` value, or escape the existing ones.

## Challenge Seed

```js
"use strict"

let innerHtml = "<p>Click here to <a href="#Home">return home.</a></p>"
console.log(innerHtml);
```

## Challenge Tests

```
assert(code.test(/href=('|\")#Home('|\")/gi), 'message: Fix the quotes around the <code>href</code> value "#Home" by either changing or escaping them.');
```

## Challenge Solution

```js
"use strict"

let innerHtml = "<p>Click here to <a href='#Home'>return home.</a></p>"
console.log(innerHtml);
```

**Comment by HKuz** [comment]
# Catch Use of Assignment operator Instead of Equality Operator (= VS == and ===)

## Challenge Description

Branching programs, aka ones that do different things if certain conditions are met, rely on `if`, `else if`, and `else` statements in JavaScript. The condition sometimes takes the form of testing whether a result is equal to a value. How we speak this logic (in English, at least) is "if x equals y, then ..." which can literally translate into code using the `=`, or assignment operator, and unexpected control flow in your program.

As you know, the assignment operator (`=`) in JavaScript assigns a value to a variable name. And the `==` and `===` operators check for equality (the triple `===` tests for strict equality, meaning both value and type are the same). The code below assigns `x` to be 2, which evaluates as true. Almost every value on its own in JavaScript evaluates to true, except the "falsy" values of false, 0, "" (an empty string), NaN, undefined, and null.

```js
let x = 1;
let y = 2;

if (x = y) {
  // this will run for any value of y (except for a falsy)
} else {
  // this is what should run (but won't) in this example
}
```

## Instructions

Fix the condition so the program runs the right branch, and the appropriate value is assigned to `result`.

## Challenge Seed

```js
"use strict"

let x = 7;
let y = 9;
let result = "to come";

if(x = y) {
    result = "Equal!";
} else {
    result = "Not equal!";
}

console.log(result);
```

## Challenge Tests

```
assert(result == "Not equal!", 'message: Fix the code so it checks for equality, instead of using assignment in the condition.');

assert(code.test(/if\(x\s*?(==|===)\s*?y/gi), 'message: The condition can use either <code>==</code> or <code>===</code> to test for equality.');
```

## Challenge Solution

```js
"use strict"

let x = 7;
let y = 9;
let result = "to come";

if(x == y) {
    result = "Equal!";
} else {
    result = "Not equal!";
}

console.log(result);
```

**Comment by HKuz** [comment]
# Catch Missing Open and Closing Parenthesis After a Function Call

## Challenge Description

When a function or method doesn't take any arguments, you may forget to include the (empty) opening and closing parentheses when you try to call it. Often times the result of a function call is saved in a variable for other use in your code. This error can be detected when you're logging variable values (or their types) to the console and see one is set to a function reference, instead of the expected value the function returns.

The variables in the following example are different:

```js
function myFunction() {
  return "You rock!";
}

let varOne = myFunction; // set to equal a function
let varTwo = myFunction(); // set to equal the string "You rock!"
```

## Instructions

Fix the code so `result` is set to the value returned from calling `getNine`.

## Challenge Seed

```js
"use strict"

function getNine() {
    let x = 6;
    let y = 3;
    return x + y;
}

let result = getNine;
console.log(result);
```

## Challenge Tests

```
assert(result == 9, 'message: Fix the code so the variable <code>result</code> is the number that the function <code>getNine</code> returns.');

assert(code.test(/getNine\(\);/gi), 'message: Make sure to call the <code>getNine</code> function.');
```

## Challenge Solution

```js
"use strict"

function getNine() {
    let x = 6;
    let y = 3;
    return x + y;
}

let result = getNine();
console.log(result);
```

**Comment by HKuz** [comment]
# Catch Arguments that are Passed in the Wrong Order when Calling a Function

## Challenge Description

Continuing our discussion on calling functions, the next bug to watch out for is when a function's arguments are supplied in the incorrect order. If the arguments are different types, such as a function expecting an array and an integer, this will likely throw a runtime error. If the arguments are the same type (all integers, for example), then the logic of the code won't make sense. Make sure to supply all required arguments, in the proper order to avoid these issues.

## Instructions

The following function `positivePowers` raises a base to a positive exponent. Unfortunately, it's not called properly - fix the code so the value of `test` is the expected 8.

## Challenge Seed

```js
"use strict"

function positivePowers(b, e) {
    let result = 1;
    if (e <= 0) return result;
    for (let i = 1; i <= e; i++) {
        result *= b;
    }
    return result;
}

let base = 2;
let exp = 3;
let test = positivePowers(exp, base);
console.log(test);
```

## Challenge Tests

```
assert(test == 8, 'message: Fix the code so the variable <code>text</code> equals 2 raised to the 3rd power, not 3 raised to the 2nd power.');

assert(code.test(/positivePowers\(\s*?base,\s*?exp\s*?\);/gi), 'message: Make sure the arguments for the <code>positivePowers</code> function call are in the right order.');
```

## Challenge Solution

```js
"use strict"

function positivePowers(b, e) {
    let result = 1;
    if (e <= 0) return result;
    for (let i = 1; i <= e; i++) {
        result *= b;
    }
    return result;
}

let base = 2;
let exp = 3;
let test = positivePowers(base, exp);
console.log(test);
```

**Comment by QuincyLarson** [comment]
@HKuz wow - amazing work. These are really well designed and well-written! And you've knocked this out so quickly (only one challenge left).

On this challenge, can we use a test to verify they used the typeOf command some how? https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243161254

**Comment by HKuz** [comment]
@QuincyLarson thank you! And yes, I can re-work the typeof challenge and test it using regex. I've been checking my tests as much as I can on my machine and on CodePen, time will tell if they actually work in the seed code...

I think I'll add 1-2 more challenges to at least cover "off by one" indexing errors. And if you don't mind, I was going to put myself as the owner for the topic :)

**Comment by HKuz** [comment]
# Use Caution when Reinitializing Variables inside a Loop

## Challenge Description

Sometimes it's necessary to save information, increment counters, or re-set variables within a loop. A potential issue is when variables either should be reinitialized, and aren't, or vice versa. This is particularly dangerous if you accidentally reset the variable being used for the terminal condition, causing an infinite loop.

Printing variable values with each cycle of your loop by using  `console.log()` can uncover buggy behavior related to resetting, or failing to reset a variable.

## Instructions

The following function is supposed to create a two-dimensional array with `m` rows and `n` columns of zeroes. Unfortunately, it's not producing the expected output because the `row` variable isn't being reinitialized in the outer loop. Fix the code so it returns a correct 3x2 array of zeroes ([[0, 0], [0, 0], [0, 0]]).

## Challenge Seed

```js
"use strict"

function zeroArray(m, n) {
    // Creates a 2-D array with m rows and n columns of zeroes
    let newArray = [];
    let row = [];
    for (let i = 0; i < m; i++) {
        // Adds m rows into newArray
        
        for (let j = 0; j < n; j++) {
            // Adds n zeroes into the current row
            row.push(0);
        }
        newArray.push(row);
    }
    return newArray;
}

let test = zeroArray(3, 2);
console.log(test);
```

## Challenge Tests

```
assert(JSON.stringify(test) === "[[0,0],[0,0],[0,0]]", 'message: <code>test</code> should be an array holding 3 rows of 2 columns of zeroes each.');

assert(test.length === 3, 'message: <code>test</code> should have 3 rows.');

assert(test[0].length === 2 && test[1].length === 2 && test[2].length === 2, 'message: <code>test</code> should have 2 columns in each row.');
```

## Challenge Solution

```js
"use strict"

function zeroArray(m, n) {
    // Creates a 2-D array with m rows and n columns of zeroes
    let newArray = [];    
    for (let i = 0; i < m; i++) {
        // Adds m rows into newArray
        let row = [];
        for (let j = 0; j < n; j++) {
            // Adds n zeroes into the current row
            row.push(0);
        }
        newArray.push(row);
    }
    return newArray;
}

let test = zeroArray(3, 2);
console.log(test);
```

**Comment by HKuz** [comment]
# Catch "Off By One" Errors when Using Indexing

## Challenge Description

"Off by one" errors (sometimes called OBOE) crop up when you're trying to target a specific index of a string or array (to slice or access a segment), or when looping over the indices of them. As you know, JavaScript indexing starts at zero, not one, which means the last index is always one less than the length of the item. If you try to access an index equal to the length, the program may throw an "index out of range" reference error or print `undefined`. Also, read the documentation for any string or array methods that take index ranges as arguments, and understand if they are inclusive (the item at the given index is part of what's returned) or not.

Here are some examples of off by one errors:

```js
let alphabet = "abcdefghijklmnopqrstuvwxyz";
let len = alphabet.length;

for (let i = 0; i <= len; i++) {
    // loops one too many times
    console.log(alphabet[i]);
}

for (let j = 1; j < len; j++) {
    // loops one too few times and misses the first character at index 0
    console.log(alphabet[j]);
}

for (let k = 0; k < len; k++) {
    // Goldilocks approves - this is just right
    console.log(alphabet[k]);
}
```

## Instructions

Fix the two indexing errors in the following function so all the numbers 1 through 5 are printed to the console.

## Challenge Seed

```js
"use strict"

function countToFive() {
    let firstFive = "12345";
    let len = firstFive.length;
    for (let i = 1; i <= len; i++) {
        console.log(firstFive[i]);
    }
}

countToFive();
```

## Challenge Tests

```
assert(code.test(/let i\s*?=\s*?0\s*?;\s*?i\s*?<\s*?len\s*?;/g), 'message: Fix both the initial condition for <code>i</code> and the loop's terminal condition so all five numbers are printed to the console.');
```

## Challenge Solution

```js
"use strict"

function countToFive() {
    let firstFive = "12345";
    let len = firstFive.length;
    for (let i = 0; i < len; i++) {
        console.log(firstFive[i]);
    }
}

countToFive();
```

**Comment by HKuz** [comment]
# Prevent Infinite Loops with a Valid Terminal Condition

## Challenge Description

Our final topic is the dreaded infinite loop. Loops are great tools when you need your program to run a code block a certain number of times or until a condition is met, but they need a terminal condition that ends the looping. Infinite loops are likely to freeze or crash the browser, and cause general program execution mayhem, which no one wants.

We saw an example of an infinite loop in the introduction - there is no terminal condition to break out of this `while` loop:

```js
function loopy() {
  while(true) {
      console.log("Hello, world!");
  }
}
```

It's the programmer's job to ensure that the terminal condition, which tells the program when to break out of the loop code, is eventually reached. Some errors include incrementing or decrementing a counter variable in the wrong direction from the terminal condition, or accidentally resetting a counter or index variable within the loop code, instead of incrementing or decrementing it.

## Instructions

The below function contains an infinite loop because the terminal condition `i != 4` will never be reached - `i` will increment by 2 each pass, and jump right over 4 since it's odd to start. Fix the comparison operator in the terminal condition so the loop only runs for `i` up to 4.

## Challenge Seed

```js
"use strict"

function myFunc() {
    for (let i = 1; i != 4; i += 2) {
        console.log("Still going!");
    }
}
```

## Challenge Tests

```
assert(code.test(/for\s*?\(\s*?let i\s*?=\s*?1;\s*?i\s*?(<=|<)\s*?4\s*?;\s*?i\s*?\+=\s*?2\s*?\)/g), 'message: Only change the comparison operator of <code>!=</code> in the terminal condition so the loop terminates for values bigger than 4. Don't change any other parts of the loop statement.');
```

## Challenge Solution

```js
"use strict"
function myFunc() {
    for (let i = 1; i <= 4; i += 2) {
        console.log("Still going!");
    }
}
```

**Comment by QuincyLarson** [comment]
@HKuz wow - excellent work. "Off by one errors" is a great idea - this is one of the most common types of bugs that people introduce. 

It looks like this section is done. I'm going to close it and you can re-open it if you have any further ideas for challenges later. I'll start importing it into the seed file. Congratulations on designing and implementing these challenges in record time!
