### ISSUE TITLE
QA Process

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#52]
👍  = all challenges designed
🎱  = not all challenges designed yet
💯  = has been QA'd
💌  = intro text created
❗ = priority for @HKuz
☑️ = completely ready
- [x] [Applied Visual Design](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/7)  👍 💯 💌
- [x] [Applied Accessibility]() 👍 💯 💌
- [x] [Responsive Web Design](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/10)  👍 💯 💌
- [x] [CSS Flexbox](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/21) 👍 💯 💌
- [ ] [ES6](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/34) 🎱 
- [x] [Regular Expressions](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/22) 👍 💯 💌
- [x] [Debugging](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47)  👍 💌 💯
- [x] [Object Oriented Programming](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/15)  👍 💯 💌❗ 
- [x] [Functional Programming](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/16) 👍 💯 💌❗ 
- [ ] [Advanced Data Structures](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/17) 🎱 
- [x] [Sass](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/1) 👍 💯 💌 ❗ 
- [ ] [React](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/2) 👍💯 💌
- [ ] [Redux](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/3) 👍
- [ ] [React and Redux](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/4) 👍 
- [x] [Data Visualization with D3](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/20) 🎱 💯 💌 ❗ 
- [x] [JSON APIs and AJAX](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/27) 👍 💯 💌❗
- [ ] [Managing Packages with npm](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44) 👍 💌
- [ ] [Node and Express](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44) 👍 💌 
- [ ] [MongoDB and Mongoose](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44) 👍 💌
- [ ] [Information Security with Helmet.js](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44)  👍 
- [ ] [Quality Assurance and Testing with Chai](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/48)  👍  
- [ ] [Advanced Node.js methods](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/49) 🎱

**Comment by HKuz** [comment]
### Sections or Challenges that Require Functionality Updates to Run:

#### Sass
- the way the seed code is structured, CSS is written in a `style` tag then followed by HTML in the same view. When the Sass syntax is written in the `style` tags, it's not being properly converted into CSS syntax, and applied to the HTML. Any Sass written by the camper in the challenge doesn't process properly, so that styling doesn't show in the mobile phone output area. While it happens for the entire section, this affects ~5 challenges specifically since their assert tests check for certain CSS styles being applied to elements. Those tests currently always fail.

#### JSON APIs and Ajax
- the "Post Data with the JavaScript" challenge doesn't respond properly. It asks the camper to enter his/her name and on clicking "Send Message", the name is supposed to be sent to the server which then responds with "[Name] loves cats." Currently there is no FCC API which supports this, for the challenge to work it needs to be added at some point. (Once this feature is added to FCC API, the challenge will need to be updated to include the exact URL for the request)

**Comment by QuincyLarson** [comment]
@HKuz thanks for the update. I am meeting with @BerkeleyTrue tomorrow morning and we will discuss this. Our goal is to get you unblocked on this as quickly as possible! :)

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! We've loaded these challenges into the seed files and plan to deploy them to beta as soon as possible. 

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
