### ISSUE TITLE
Create individual landing pages for each section

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#56]
Certificates: 
- [ ] Responsive Web Design
- [ ] JavaScript Algorithms and Data Structures
- [ ] Front End Libraries
- [ ] Data Visualization
- [ ] APIs and Microservices
- [ ] Information Security and Quality Assurance

Topics:
- [ ] [Basic HTML5 and CSS3](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/6) 
- [ ] [Applied Visual Design](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/7) 
- [ ] [Responsive Web Design](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/10)  
- [ ] [CSS Flexbox](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/21) 
- [ ] Applied Accessibility
- [ ] Applied User Experience
- [ ] Responsive Web Design Projects
- [ ] [Basic JavaScript](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14) (includes ES6)
- [ ] [Regular Expressions](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/22)
- [ ] [Debugging](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47)
- [ ] Basic Algorithm Scripting
- [ ] [Object Oriented Programming](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/15) 
- [ ] [Functional Programming](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/16)
- [ ] Intermediate Algorithm Scripting
- [ ] [Advanced Data Structures](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/17)
- [ ] Advanced Algorithm Scripting
- [ ] Boostrap (this should also mention Font Awesome and Animate.css)
- [ ] jQuery 
- [ ] [Sass](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/1) 
- [ ] [React](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/2) 
- [ ] [Redux](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/3)
- [ ] [React and Redux](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/4) 
- [ ] Front End Library Projects
- [ ] [Data Visualization with D3](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/20)
- [ ] [JSON APIs and AJAX](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/27)
- [ ] Data Visualization Projects
- [ ] [Managing Packages with npm](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44)
- [ ] [Node and Express](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44)
- [ ] [MongoDB and Mongoose](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44)
- [ ] API and Microservice projects
- [ ] [Information Security with Helmet.js](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44)
- [ ] [Quality Assurance and Testing with Chai](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/48)
- [ ] [Advanced Node.js methods](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/49)
- [ ] Information Security and Quality Assurance Projects
