### ISSUE TITLE
Split HTML and CSS into separate sections

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#74]
We plan to start off the curriculum with a handful of HTML-only challenges, for simplicity's sake.

We need to rework the initial challenges so that the following challenges flow together seamlessly:
- [x] Say Hello to HTML Elements - [UPDATE TEXT](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-254080698)
- [x] Headline with the h2 Element
- [x] Inform with the Paragraph Element
- [x] [Introduction to HTML5 Elements](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-254062082) - NEW/Complete
- [x] Fill in the Blank with Placeholder Text
- [x] Add Images to your Website
- [x] Uncomment HTML
- [x] Comment out HTML
- [x] Link to External Pages with Anchor Elements
- [x] [Link to Internal Sections with Anchor Elements](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-255181089) - NEW/Complete
- [x] Nest an Anchor Element within a Paragraph Incomplete
- [x] Make Dead Links using the Hash Symbol Incomplete
- [x] Turn an Image into a Link Incomplete
- [x] Create a Bulleted Unordered List Incomplete
- [x] Create an Ordered List Incomplete
- [x] Create a Text Field Incomplete
- [x] Add Placeholder Text to a Text Field Incomplete
- [x] Create a Form Element Incomplete
- [x] Add a Submit Button to a Form Incomplete
- [x] Use HTML5 to Require a Field Incomplete
- [x] Create a Set of Radio Buttons Incomplete
- [x] Create a Set of Checkboxes Incomplete
- [x] Check Radio Buttons and Checkboxes by Default Incomplete
- [x] Nest Many Elements within a Single Div Element
- [x] Fill in the Blank with Placeholder Text Incomplete
- [x] [Declare the Doctype of an HTML Document](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-271568467) - NEW/Complete
- [x] [Define the Head and Body of an HTML Document](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-271568467)- NEW/Complete

Then we need to rework the remaining CSS challenges to flow together seamlessly:
- [x] Change the Color of Text 
- [x] Use CSS Selectors to Style Elements 
- [x] Use a CSS Class to Style an Element 
- [x] Style Multiple Elements with a CSS Class 
- [x] Change the Font Size of an Element 
- [x] Set the Font Family of an Element 
- [x] Import a Google Font 
- [x] Specify How Fonts Should Degrade 
- [x] Size your Images 
- [x] Add Borders Around your Elements 
- [x] Add Rounded Corners with a Border Radius 
- [x] Make Circular Images with a Border Radius 
- [x] Give a Background Color to a Div Element 
- [x] Set the ID of an Element 
- [x] Use an ID Attribute to Style an Element
- [x] Adjusting the Padding of an Element 
- [x] Adjust the Margin of an Element 
- [x] Add a Negative Margin to an Element 
- [x] Add Different Padding to Each Side of an Element 
- [x] Add Different Margins to Each Side of an Element 
- [x] Use Clockwise Notation to Specify the Padding of an Element 
- [x] Use Clockwise Notation to Specify the Margin of an Element 
- [x] [Understand Absolute versus Relative Units](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/74#issuecomment-254063222) - NEW/Complete
- [x] Style the HTML Body Element 
- [x] Inherit Styles from the Body Element 
- [x] Prioritize One Style Over Another 
- [x] Override Styles in Subsequent CSS 
- [x] Override Class Declarations by Styling ID Attributes 
- [x] Override Class Declarations with Inline Styles 
- [x] Override All Other Styles by using Important 
- [x] Use Hex Code for Specific Colors 
- [x] Use Hex Code to Mix Colors 
- [x] Use Abbreviated Hex Code 
- [x] Use RGB values to Color Elements 
- [x] Use RGB to Mix Colors

**Comment by gbsimon87** [comment]
As an intermediate programmer, but someone who now basically lives at FCC, this looks like something I could handle to begin contributing.  
Please inform if this is a possibility.
In addition, when you say 'rework', do you mean change the wording/order of the problems to find a transition that is easier/simpler to understand?
If I may, I'd recommend starting off with HTML (as you've stated), then inline, internal, and lastly external CSS.  This approach would give the campers the understanding that CSS can be implemented in many manners, can teach them which method will take precedence, and can lead to emphasizing the importance of having an external style sheet that may be used for one or more pages.
The HTML5/CSS3 for dummies book took this approach and when I read it years ago I grasped it straight away.
Before all this, however, I feel there should be an intro as to what each language does for a website.
Perhaps through the use of an analogy, for example, building a house:
HTML is for the blueprint (raw layout), CSS is for the decorations (colors and touch-ups), and JS is for the functionalities (the water comes out of the tap the second you put your hand in the sink).
I feel if campers are aware, from the very beginning, of what they are about to learn and what it can do, it may bring to light a lot of the obscurity they may be faced with.
I know this would have helped me when I started my jQuery lessons on FCC without having the slightest clue of what it was.
Just a friendly two cents.
Once again, please inform if this is something I'd be able to contribute with, a man needs to start somewhere! :)

**Comment by HKuz** [comment]
@gbsimon87 - new contributors are always welcome! I'd imagine the rework for this section will include the reorder, then a review of the text of each challenge to make sure it doesn't reference something that hasn't been taught. Then just make sure they read smoothly from one to the next - after a reorder you just need to make sure any references to 'in the last/next challenge' are valid.

@QuincyLarson - what would the workflow look like for these sections, given that the challenges are being continually updated/improved on the Staging branch? I can imagine if we start editing text on the `feature/curriculum-expansion` branch we could run into merge conflicts?

And @gbsimon87 others on this repo agree with your point about having introductory text for each section to give campers a high-level overview of what they're about to learn 😄  The plan is to add landing pages before each section. Check out issue #45 for the general premise, or if you want to take a look at what's been done for the new curriculum expansion topics, I've linked to a few drafts here. Ultimately, I believe the plan is to have them for every section:

[JSON and APIs](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/27#issuecomment-252729386)
[Applied Visual Design](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/7#issuecomment-249335858)
[Debugging](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/47#issuecomment-243167181)
[Applied Accessibility](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/9#issuecomment-240578639)
[Responsive Web Design](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/10#issuecomment-249644886)
[Regular Expressions](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/22#issuecomment-249419147)

**Comment by QuincyLarson** [comment]
@gbsimon87 Yes - as @HKuz said we will have introductions to each of these sections.

@HKuz We can push directly to the curriculum expansion branch. We don't need to do pull requests against it. Since a vast majority of the final challenge work (inputting, editing, and QA'ing) we shouldn't encounter significant merge conflicts, and if we do, we can address them together on a call.

**Comment by HKuz** [comment]
Okay, thanks @QuincyLarson 

@gbsimon87 - if you're interested in writing the introductory text for these two sections, you're welcome to! You can post drafts here, similar to what we've done in the links I posted above. I wouldn't mention JavaScript in them, as each intro should cover the topic of the section without mentioning something that hasn't been taught in the FCC curriculum yet. Also, we've been aiming to keep language simple and straightforward, since there are a lot of non-native English speakers using FCC. (@QuincyLarson turned me onto the [Hemingway Editor](http://www.hemingwayapp.com/) that helps me with this)

For a reorder, if you'd like to copy the list in the original post, and re-paste it with your suggestions, that could work! Once we agree on an order, then we can go in and make changes in the code base and check for consistent language, etc. 

@QuincyLarson - my QA 'to-do' list for this topic includes making sure any new challenges or suggestions that were proposed in #6 get seeded, QA'd and added to the sequence above. Some of the suggestions are covered with challenges in other sections, but I saw at least one challenge introducing HTML5 elements that we'll need to pull in here.

**Comment by QuincyLarson** [comment]
@HKuz OK - great. When you get a chance, perhaps you could find those challenges and add them to the list? We may be able to cover some of these HTML5 abilities in the accessibility section, since it is heavily HTML5 focused.

**Comment by HKuz** [comment]
(Copied from issue #6)

# Introduction to FreeCodeCamp’s Development Environment

## Challenge Description:

This is FreeCodeCamp’s in-browser development environment. This is where we will build our web pages with HTML (Hyper Text Markup Language), and style them with CSS (Cascading Style Sheets). Don’t worry if you have never heard of HTML and CSS before, we will got into more detail as you progress through the FreeCodeCamp curriculum.

Quick tour through the IDE - need to know what it will look like to complete this section

To move on to the next challenge, please click the ‘Run Tests’ tests button.

## Challenge Seed:
```js
''
```

## Challenge Tests:
assert(true);

**Comment by HKuz** [comment]
(Copied from issue #6)

# Introduction to HTML5 Elements

## Challenge Description

HTML5 introduces more descriptive HTML tags. These include <code>&lt;header&gt;</code>, <code>&lt;footer&gt;</code>, <code>&lt;nav&gt;</code>, <code>&lt;video&gt;</code>, <code>&lt;article&gt;</code>, <code>&lt;section&gt;</code> and others.

These tags not only make your HTML easier to read, it also helps with Search Engine Optimization (SEO) and accessibility.

The <code>&lt;main&gt;</code> HTML5 tag helps search engines and other developers find the main content of your page.

Note: Many of the new HTML5 tags and their benefits will be covered in the Applied Accessibility section.

<h4>Instructions</h4>

Wrap the paragraph with a opening and closing <code>main</code> tag.

## Challenge Seed

```html

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

## Challenge Tests

```js
assert($('main').length === 1, 'message: Your code should use a <code>main</code> tag.');
assert(code.match(/<main>\s*?<p>/g), 'message: Add an opening <code>main</code> tag before the paragraph.');
assert(code.match(/<\/p>\s*?<\/main>/g), 'message: Add a closing <code>main</code> tag after your paragraph.');
```

## Challenge Solution

```html
<h2>CatPhotoApp</h2>

<main><p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p></main>
```

**Comment by HKuz** [comment]
(Suggested in issue #6)

# Understand Relative versus Absolute Units

## Challenge Description

[To Come]

## Challenge Seed

```html
```

## Challenge Tests

```js
```

## Challenge Solution

```html
```

**Comment by QuincyLarson** [comment]
@HKuz I recommend we just start by introducing HTML (and not CSS). Here are some things we'd need to explain:

Welcome to Free Code Camp's coding challenges. These will walk you through web development step-by-step. 

We recommend you do these in order, but feel free to skip around by clicking the map on the left.

Also, if you want to save your progress, you should join our community by creating an account. In just a few minutes, you can join our chat room, forum, and even a local study group in your city.

First, you'll start by building a simple web page using HTML. Change the H1 element to say "Hello World". Notice how this updates the preview.

When you're done, click the "Run Test" button, and the test below will change from red to green. Then you can go to the next coding challenge.

**Comment by HKuz** [comment]
Sounds good 👍 - looking at your suggestion and what is currently in the first challenge ("Say Hello to HTML Elements"), I don't think this is a new challenge - we can just update the current first challenge. I'll update the list above to reflect that.

**Comment by QuincyLarson** [comment]
@HKuz Yes - I figure we can just update the initial challenge. It's so easy, it's basically just an opportunity to show people around.

**Comment by dhcodes** [comment]
# Link to Internal Sections of a Page with Anchor Elements

## Challenge Description

In addition to creating external links, anchor elements can also be used to create internal links, which are links that jump to different sections within a webpage.

The format is similar to an external link except instead of a url, you'll use the `<code>#</code>` and the name of the section you want to jump to.

Here's an example:
<code><a href="#contact">Go to contact section</a></code>

Next, you'll want to create a corresponding anchor link in the HTML where you want the internal link to take users, but instead of using the <code>href</code> attribute you'll use the <code>name</code> attribute, as below. 

Here's an example:
<code>
<h1>Contact</h1>
<a name="contact"></a>
</code>

Now when a user clicks the "Go to contact section" link, he/she will be taken to the contact section of the same webpage.

<h4>Instructions</h4>

Change your external link to an internal link by changing the <code>href</code> attribute to <code>#bottom</code> and the anchor text from "cat photos" to "Jump to Bottom".

Then add an anchor link with a name attribute of "bottom" after the last paragraph.

<strong>Note:</strong>
More kitty ipsum text has been added to the paragraphs to better show the effect of clicking the link to jump to the corresponding section.

## Challenge Seed

```html
<link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\" type=\"text/css\">",
        "<style>",
        "  .red-text {",
        "    color: red;",
        "  }",
        "",
        "  h2 {",
        "    font-family: Lobster, Monospace;",
        "  }",
        "",
        "  p {",
        "    font-size: 16px;",
        "    font-family: Monospace;",
        "  }",
        "",
        "  .thick-green-border {",
        "    border-color: green;",
        "    border-width: 10px;",
        "    border-style: solid;",
        "    border-radius: 50%;",
        "  }",
        "",
        "  .smaller-image {",
        "    width: 100px;",
        "  }",
        "</style>",
        "",
        "<h2 class=\"red-text\">CatPhotoApp</h2>",
        "",
        "<img class=\"smaller-image thick-green-border\" src=\"https://bit.ly/fcc-relaxing-cat\" alt=\"A cute orange cat lying on its back. \">",
        "",
        "<p class=\"red-text\">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>",
        "<p class=\"red-text\">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>"

```

## Challenge Tests

```js

```

## Challenge Solution

N/A

**Comment by HKuz** [comment]
Nice, @dhcodes!

**Comment by QuincyLarson** [comment]
@dhcodes great work! Minor nitpick: instead of using he/she just use "they" which is now widely accepted as a singular pronoun, and a lot less clunky :)

@HKuz and I will eventually get around to creating a style guide for these challenges descriptions 🙂

**Comment by HKuz** [comment]
@QuincyLarson agreed on creating a style guide 👍 - I have a checklist in my mind of what I go through reading all the new challenges, and can put it down at some point as a start 😄. One thing (I think was discussed in this issue somewhere but I can't find the comments) is whether the challenge text should use "we/let's", "you", or if both are okay. Right now some sections use "you", some use "we" - I tried to limit the use of either, but it's hard to avoid all together without making the text sound awkward.

**Comment by QuincyLarson** [comment]
@HKuz I recommend using 2nd person throughout. Google has created a good style guide for interfaces, though I'd argue much of this applies for challenge directions as well: https://material.google.com/style/writing.html

I've written a style guide of my own for Medium that might be helpful: https://medium.freecodecamp.com/a-style-guide-for-writing-on-medium-fcbad27492ea#.hxj5qm1vw

And Mailchimp has a content strategy guide here: http://styleguide.mailchimp.com/writing-technical-content/

**Comment by atharvajava** [comment]
```

**# HTML-Here To Make Love**

What is HTML ?

HTML is a markup language where HTML stands for HyperText Markup Language where HyperText can be understood as collection of hyperlinks to hop over several other pages and Markup can be taken as collection of symbols or anything which can be referred as symbol here in HTML we can call the tags as markup. There are several types of tags in HTML which you will get to know as you go through this course. 

In this course we will be mainly focusing on HTML5 , there are many new element's introduced in the new version in comparison with previous generation like HTML5 video which was the actual cause of the flash death as you might have noticed that the youtube player is somewhat different now from what it was like 2 years ago. This was officially released in 2011 .

So, Are we ready to say cheers to Html and ready to make love with it :D haha!!! 
```

This is a rough stuff i came up with if this looks good i will work on making it better if not then give me more clarification on how you guys want it to be.

**Comment by dhcodes** [comment]
@HKuz Below is a first go at the intro page for CSS. You can give me feedback here or via Gitter. Also, feel free to make edits directly in this post.

# CSS

Cascading Style Sheets (CSS) tell the browser how to display the text and other content that you write in HTML. CSS has been adopted by all major browsers and allows you to manipulate:
- colors
- fonts
- positioning
- spacing
- sizing
- decorations
- transitions

CSS can be applied both as inline styles--typed directly within your HTML tags--or external style sheets--typed in a separate file that is referenced from a separate file. The latter is the preferred method as it keeps the styles separate from the HTML elements, therefore improving the readability and reusability of your code.

The idea behind CSS is that you can use a selector to target an HTML element in the DOM (Document Object Model) and then apply a variety of attributes to that element to change the way it is displayed on the page.

In this section, you'll see how adding CSS styles to the elements of your CatPhotoApp can change it from simple text to something more.

**Comment by oppiniated** [comment]
I've seen users struggle on why a particular  style was applied, or why a css rule they created was overwritten. I'd like to suggest a set of challenges based around the **Specificity of CSS**. So users can have a better understanding of CSS

**Comment by QuincyLarson** [comment]
@atharvajava thanks for adding this description. This is definitely something @HKuz can work with as she prepares this description.

@oppiniated The CSS challenges I created a long time ago do cover specificity and prominence (as explained here: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) and !important though we never covered "not" 

Would you be interested in designing a challenge that covers this?

**Comment by atharvajava** [comment]
HTML
What is HTML?
HTML is a Mark-up language, here HTML stands for HyperText Mark-up Language where HyperText can be understood as collection of hyperlinks to hop over several other pages and Mark-up can be taken as collection of symbols or anything which can be referred as symbol here in HTML we can call the tags as mark-up.
There are several types of tags in HTML which you will get to know as you go through this course.
In this course we will be mainly focusing on HTML5 , there are many new element's introduced in the new version in comparison with previous generation like HTML5 video which was the actual cause of the flash death as you might have noticed that the YouTube player is somewhat different now from what it was like 2 years ago.
HTML5 was officially released on 2011. You can further read search ask about previous generation of HTML.
So, are we ready to say cheers to HTML?

@QuincyLarson  @HKuz  I made few minor tweaks as suggested My grammer might not be as good as other's so please correct me on that. Also if this looks fine i will start working on something else and if not i ll try to improvise this one more.  

On ES6 I was thinking of assisting @alayek  but I am not so sound in javascript as of now and alek told me to learn ES6 first i think to do that i should also have a decent hold of js i will jump onto that after i complete FCC challanges of JS i think then will be the better time for me to contribute to that ..  Thank's

**Comment by QuincyLarson** [comment]
@atharvajava I recommend you paste your text into http://www.hemingwayapp.com/

This will help you identify the many style issues with your writing and improve its readability. Everyone can write, but actually writing well is quite difficult. But the effort is worth the effort. It will help your reader better understand these concepts.

**Comment by atharvajava** [comment]
# HTML

What is HTML?

HTML is a Mark-up language, here HTML stands for HyperText Mark-up Language.

Where we can understand HyperText,as collection of hyperlinks to hop over several other pages. And Mark-up means collection of symbols. Here in HTML we can call the tags(<>) as Mark-up.


There are several types of tags in HTML which you will get to know as you go through this course.


In this course we will be focusing on HTML5. HTML5 first came in 2011. There are many new element's introduced in HTML5 over previous generation like : 

- HTML5 video,
- Canvas
- Web Workers
- Application Caches
- Geo Location 
- 
- HTML5 video,
- Canvas
- Web Workers
- Application Caches
- Geo Location 
- 

As we have finally seen flash death which seemed kind of impossible before the release of HTML5. You might have noticed that youtube also switched to HTML5 player.

 You can further read search ask about previous generation of HTML. 
So, are we ready to say cheers to HTML?

I hope this looks readable now ... tried editing it as per hemingway :)

**Comment by oppiniated** [comment]
@atharvajava HTML5 introduces some new elements and APIs. The first two items in your list are new elements + API. The last three are new APIs.

**Comment by oppiniated** [comment]
@QuincyLarson I'd be glad to be able to device a challenge based that would cover this use case. I'd like some help and direction with this.

Best,
O

**Comment by HKuz** [comment]
@atharvajava thanks for your changes per our last conversation - as @QuincyLarson mentioned, I can certainly work with what you've posted. Thank you! 

@oppiniated that would be fantastic if you'd like to create the suggested challenge! Here are a couple resources and comments to get started:

- [The challenge style guide in this repo](https://github.com/FreeCodeCamp/CurriculumExpansion/blob/master/challenge-style-guide.md)
- Here's [the new challenge template](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/6#issue-163615115) - you can post the challenge right here as a comment when it's ready
- Check out the comments in issue #55 - there are suggestions helping another camper write new challenges. Specifically in that issue there was [this comment with info about writing tests](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/55#issuecomment-251688618)
- Here's a [comment about styles for introductory text](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/45#issuecomment-257659648). It's geared towards writing the introductions for each section, but the bullet points can apply to new challenges, too

If you want to check out how others have written new challenges, basically this repository had a separate issue for each new topic and the challenges were posted as comments. For example, the ones I wrote on Accessibility are in #9.

If you have questions, you can post them here, ask in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors), or message me directly in Gitter.

Thanks so much! 🎉

**Comment by QuincyLarson** [comment]
A quick update: I talked with @HKuz tonight and she plans to split these sections up and create new challenges as necessary.

**Comment by smileytechguy** [comment]
Can I be assigned any of the above?  Thanks

**Comment by HKuz** [comment]
@smileytechguy - yes, you can write the new suggested challenges and post them here 👍 

Here's a list of potential new challenges that have not been written yet. I've made some sequencing suggestions for each based on the list at the top of this post, but use your best judgement:
- Understand Absolute versus Relative Units (see the list up top for its order)
- Challenges to cover !DOCTYPE/ `html`, `head`, and `body` - see #55 for the full discussion in the comments. They should come at the end of the HTML section
- A challenge or two to cover CSS nesting [discussed here](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/7#issuecomment-259543322). Those may make sense towards the end of the CSS section, maybe before or after the specificity ones.

The trick to these is that they need to fit in with the challenges around them, so take a look at the exisiting FCC challenges and try your best to get them to flow. I'll be splitting the sections apart per the list above, and will likely have to make tweaks in this department, too.

You can post your work here! Take a look at my comment right above here for a general style guide to writing challenges.

Thanks so much, @smileytechguy 🎉

**Comment by smileytechguy** [comment]
@HKuz Alright, I'll work on `Challenges to cover !DOCTYPE/ html, head, and body - see #55 for the full discussion in the comments. They should come at the end of the HTML section`
Thanks!

**Comment by smileytechguy** [comment]
I think we should also include various `<link>`, `<meta>`, `<title>` elements, and other elements for the `<head>` element. What do you guys think?

**Comment by smileytechguy** [comment]
# HTML Page Structure

Alright, so we've learned about what _goes_ into a HTML page, but there is some organizational elements that haven't been discussed yet:

First, we need to tell the browser what version of HTML we are using.  Most all browsers support HTML5, so we can just use the html5 specification.

We do this by adding `<!DOCTYPE html>` to the beginning of our document.

The `!` and uppercase `DOCTYPE` is extremely important, especially for older browsers.  The `html` is case insensitive.

If you want to learn more about valid DOCTYPEs, you can look at the [W3 Consortium's page](https://www.w3.org/QA/2002/04/valid-dtd-list.html).

Now, the entire page must be wrapped in a `<html>` element.  The `<html>` goes directly below the `<!DOCTYPE html>` line, and the corresponding `</html>` goes at the end of the page.

Next, all metadata elements such as `<link>`, `<meta>`, `<title>` and other elements not displayed to the user go into the `<head>` element.

After the `<head>` element, the rest of the page (what the user sees) goes into a `<body>` element.

Therefore, a page's layout should look like this:

```html
<!DOCTYPE html>
<html>
<head>
	<!-- metadata elements -->
</head>
<body>
	<!-- page contents -->
</body>
</html>
```

In order to complete this challenge, organize the following page.

## Challenge Seed

Todo

## Solution Code

Todo

## Tests

Todo

**Comment by smileytechguy** [comment]
Someone please look over the above challenge.  I think all the structure elements should be covered together.

**Comment by QuincyLarson** [comment]
@smileytechguy @HKuz has a pretty good handle on which tasks need to be done to accomplish this. Would you be interested in helping design a few more advanced algorithm / data structure challenges?

**Comment by smileytechguy** [comment]
@QuincyLarson yeah sure, however all i see available is graph traversal and I'm not sure how to do that yet.

**Comment by QuincyLarson** [comment]
@smileytechguy there are a ton of [help wanted issues on our core repo](https://github.com/FreeCodeCamp/FreeCodeCamp/labels/help%20wanted) if you're interested in those. Once we transitioning these challenges to the staging branch, it will be easier to hop in and work on them.

**Comment by HKuz** [comment]
@smileytechguy -thanks for writing that challenge! I actually split it up into two - one that covers DOCTYPE and `html` tags, and one that covers `head` and `body`. Plan is to get the new challenges seeded when these sections are split apart. Stay tuned...

**Comment by smileytechguy** [comment]
Alright, thanks!

**Comment by HKuz** [comment]
@QuincyLarson - I see this issue getting ticked off up top! If you're seeding the new stuff, here are the two structure challenges (if not, it's here for completeness). They're already formatted with `code` and `blockquote` tags per FCC style, so hopefully it's just a copy paste into the json. I'll try to get to the Nested CSS challenge(s) this week.


# Declare the Doctype of an HTML Document

## Challenge Description

The challenges so far have covered specific HTML tags and their uses. However, there are a few elements that give overall structure to your page, and should be included in every HTML document.

At the top of your document, you need to tell the browser which version of HTML your page is using. HTML is an evolving language, and is updated regularly. Most major browsers support the latest specification, which is HTML5. However, older web pages may use previous versions of the language. You tell the browser this information by adding the <code>&lt;!DOCTYPE ...&gt;</code> tag on the first line, where the "..." part is the version of HTML. For HTML5, you use <code>&lt;!DOCTYPE html&gt;</code>.

The <code>!</code> and uppercase <code>DOCTYPE</code> is important, especially for older browsers. The <code>html</code> is not case sensitive.

Next, the rest of your HTML code needs to be wrapped in <code>html</code> tags.  The opening <code>&lt;html&gt;</code> goes directly below the <code>&lt;!DOCTYPE html&gt;</code> line, and the closing <code>&lt;/html&gt;</code> goes at the end of the page.

Here's an example of the page structure:

<blockquote>&lt;!DOCTYPE html&gt;<br>&lt;html&gt;<br>  &lt;!-- Your HTML code goes here --&gt;<br>&lt;/html&gt;</blockquote>

<h4>Instructions</h4>

Add a <code>DOCTYPE</code> tag for HTML5 to the top of the blank HTML document in the code editor. Under it, add opening and closing <code>html</code> tags, which wrap around an <code>h1</code> heading that can include any text.


## Challenge Seed

```html



```

## Challenge Tests

```js
assert(code.match(/<!DOCTYPE\s+?html\s*?>/gi), 'message Your code should include a <code>&lt;!DOCTYPE html&gt;</code> tag.');
assert($('html').length == 1, 'There should be one <code>html</code> element.');
assert($('html').children('h1').length == 1, 'message: The <code>html</code> tags should wrap around one <code>h1</code> element.');
```

## Challenge Solution


```html
<!DOCTYPE html>
<html>
  <h1>My Webpage!</h1>
</html>
```



# Define the Head and Body of an HTML Document

## Challenge Description

You can add another level of organization in your HTML document within the <code>html</code> tags with the <code>head</code> and <code>body</code> elements. Any markup with information about your page would go into the <code>head</code> tag. Then any markup with the content of the page (what displays for a user) would go into the <code>body</code> tag.

Metadata elements, such as <code>link</code>, <code>meta</code>, <code>title</code>, and <code>style</code>, typically go inside the <code>head</code> element.

Here's an example of a page's layout:

<blockquote>&lt;!DOCTYPE html&gt;<br>&lt;html&gt;<br>  &lt;head&gt;<br>    &lt;!-- metadata elements --&gt;<br>  &lt;/head&gt;<br>  &lt;body&gt;<br>    &lt;!-- page contents --&gt;<br>  &lt;/body&gt;<br>&lt;/html&gt;</blockquote>

<h4>Instructions</h4>

Edit the markup so there's a <code>head</code> and a <code>body</code>. The <code>head</code> should only include the <code>title</code>, and the <code>body</code> should only include the <code>h1</code> and <code>p</code>.

## Challenge Seed

```html
<!DOCTYPE html>
<html>

  <title>The best page ever</title>

  <h1>The best page ever</h1>
  <p>Cat ipsum dolor sit amet, jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Go into a room to decide you didn't want to be in there anyway. I like big cats and i can not lie kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Meow i could pee on this if i had the energy for slap owner's face at 5am until human fills food dish yet scamper. Knock dish off table head butt cant eat out of my own dish scratch the furniture. Make meme, make cute face. Sleep in the bathroom sink chase laser but pee in the shoe. Paw at your fat belly licks your face and eat grass, throw it back up kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

</html>  
```

## Challenge Tests

```js
assert($('head').length == 1, 'message: There should be only one <code>head</code> element on the page.');
assert($('body').length == 1, 'message: There should be only one <code>body</code> element on the page.');
assert($('html').children('head').length == 1, 'message: The <code>head</code> element should be a child of the <code>html</code> element.');
assert($('html').children('body').length == 1, 'message: The <code>body</code> element should be a child of the <code>html</code> element.');
assert($('head').children('title').length == 1, 'message: The <code>head</code> element should wrap around the <code>title</code> element.');
assert($('body').children('h1').length == 1 && $('body').children('p').length == 1, 'message: The <code>body</code> element should wrap around both the <code>h1</code> and <code>p</code> elements.');
```

## Challenge Solution

```html
<!DOCTYPE html>
<html>
  <head>
    <title>The best page ever</title>
  </head>
  <body>
    <h1>The best page ever</h1>
    <p>Cat ipsum dolor sit amet, jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Go into a room to decide you didn't want to be in there anyway. I like big cats and i can not lie kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Meow i could pee on this if i had the energy for slap owner's face at 5am until human fills food dish yet scamper. Knock dish off table head butt cant eat out of my own dish scratch the furniture. Make meme, make cute face. Sleep in the bathroom sink chase laser but pee in the shoe. Paw at your fat belly licks your face and eat grass, throw it back up kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  </body>
</html>  
```

**Comment by QuincyLarson** [comment]
@HKuz yes - I'm going through and adding these to the seed files and working toward prepping the PR for staging. I've been checking challenges off as I add them to the seed file. 

Thanks for creating these two new challenges. I'll import them as well 😄

**Comment by QuincyLarson** [comment]
I've finished importing this. Great work everyone, and thanks for the extra challenges, @HKuz.

Once we get these into beta, we can verify that the resequencing didn't cause anything from showing up in the challengeSeed before it's introduced.
