### ISSUE TITLE
Quality Assurance and Information Security Project: Issue Tracker

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#76]
We are updating the Dynamic Web App projects to focus 100% on their back ends, and adding additional quality assurance and information security user stories.

These projects will no longer require a front end. Instead, all the tests will be focused on JSON APIs like the API and Microservice projects. The front end will be optional and not tested.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
- I can create an account by passing an email address and password (we need a secure way to do this without having to test a UI - perhaps GitHub auth would be better)
- I can create a tweet
- I can read all recent tweets as an array of JSON
- I can read the tweets of a specific user as an array of JSON
- I can see a list of users
- I can follow another user
- I can unfollow another user
- I can retweet a tweet and it will show up in my own tweets
- I can flag a a tweet as inappropriate
- I can delete my own tweets

We can add more stories for additional testing and security issues.

Progress: 
- [ ] Create the list of tests
- [ ] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] To ask campers to build their own versions based off of our instructions and our boilerplate
- [ ] A series of tests added to Free Code Camp's seed files

**Comment by adamisntdead** [comment]
How about deleting tweets?

**Comment by QuincyLarson** [comment]
@adamisntdead Thanks - I've added this.

**Comment by JosephLivengood** [comment]
An update, the prototype and bp are done, just need to write the tests on the tester.

_Changed to Issue Tracker as to not require authentication_

*User Stories*

- Prevent cross site scripting(XSS attack).
- I can POST /api/issues/{projectname} with form data containing required issue_title, issue_text, created_by, and optional assigned_to and status_text.
- The object saved (and returned) will include all of those fields (blank for optional no input) and also include created_on(date/time), updated_on(date/time), open(boolean, true for open, false for closed), and _id.
- I can PUT /api/issues/{projectname} with a _id and any fields in the object with a value to object said object. Returned will be 'successfully updated' or 'could not update '+_id. This should always update updated_on. If no fields are sent return 'no updated field sent'.
- I can DELETE /api/issues/{projectname} with a _id to completely delete an issue. If no _id is sent return '_id error', success: 'deleted '+_id, failed: 'could not delete '+_id.
- I can GET /api/issues/{projectname} for an array of all issues on that specific project with all the information for each issue as was returned when posted.
- I can filter my get request by also passing along any field and value in the query(ie. /api/issues/{project}?open=false). I can pass along as many fields/values as I want.
- All 11 functional tests are complete and passing.

Prototype: [protective-garage](https://gomix.com/#!/project/protective-garage)

Boilerplate: [fcc-issue](https://gomix.com/#!/project/fcc-issue)

User-stories: [index](https://protective-garage.gomix.me/)

**Comment by QuincyLarson** [comment]
@JosephLivengood awesome. This looks great! I looked at it and all the tests passed. I've created a forum thread here: https://forum.freecodecamp.com/t/issue-tracker-project-with-testable-user-stories-guinea-pigs-needed/74449
